Fix assertions not reported
atoum/json-schema-extension pull request #17
Opened 2017-09-01 22:15 UTC by shouze

running tests with this extension, I got atoum reports with void methods and zero assertions whilst I expected non void & assertions reported.

2017-09-01 22:37 UTC, shouze commented
@Hywan so, with the latest commit (trusty upgrade on ci) looks like `prefer-lowest` **ALWAYS** leads to the infinite loop issue https://github.com/atoum/json-schema-extension/pull/16#issuecomment-325683054

2017-09-01 22:58 UTC, shouze commented
Ok launched ci few times and in fact... no, it's truly random.

2017-09-04 12:22 UTC, Hywan requested changes

2017-09-04 12:22 UTC, Hywan commented on classes/asserters/json.php
> +			if ($schemaObject === null) {
CS issue.

2017-09-04 12:22 UTC, Hywan commented
@shouze I don't have time to check this issue. Please, see with @jubianchi :-).

2017-09-04 12:30 UTC, shouze commented on classes/asserters/json.php
> +			if ($schemaObject === null) {
yes, fixed

2017-09-04 12:31 UTC, shouze commented
@Hywan ok no problem, in fact it's more a lot of commits that I can probably pass in separate PRs I guess.

2017-09-04 15:00 UTC, jubianchi commented
@shouze @Hywan I'm planning to issue some release today or tomorrow. I'll start with atoum and then review and merge PRs on extensions.

2017-09-04 15:11 UTC, shouze commented
@jubianchi will be available to split in more PRs if needed.

2017-09-04 19:02 UTC, jubianchi commented
@shouze don’t worry it’s fine without splitting.

But it would be awesome if you could dd the missing entries to the changelog.

Thanks!

2017-09-05 06:58 UTC, shouze commented
Yes of course, miss tests for notValidates too.

2017-09-05 20:51 UTC, shouze commented
ok @jubianchi so I've added `notValidates` tests & CHANGELOG entries, ready for a review, just that infinite loop that blocks ci randomly but everything is green otherwise.

2017-09-18 10:42 UTC, shouze commented
ping @jubianchi when you have a minute or two 👼

2017-09-25 19:27 UTC, merged